[package]
name = "rhostname"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dns-lookup = "2.0.4"
libc = "0.2.150"
sync-resolve = "0.3.1"
local-ip-address = "0.5.6"
structopt = "0.3.26"
gethostname = "0.4.3"
clap = { version = "4.4.4", features = ["derive"] }